[files]
extend-exclude = [
    "go.mod",
    "vendor",
    "vmlinux",
]
ignore-hidden = true
ignore-files = true
ignore-dot = true
ignore-vcs = true
ignore-global = true
ignore-parent = true

[default]
binary = false
check-filename = true
check-file = true
unicode = true
ignore-hex = true
identifier-leading-digits = false
locale = "en"
extend-ignore-identifiers-re = []
extend-ignore-re = [
    "(?i)aks",
    "ANDed",
    "PT_REGS_PARM",
    "Mmaped",
    "ro",
]
