apiVersion: v1
data:
  bpf-recorder.json: |
    {
      "defaultAction": "SCMP_ACT_ERRNO",
      "archMap": [
        {
          "architecture": "SCMP_ARCH_X86_64",
          "subArchitectures": [
            "SCMP_ARCH_X86",
            "SCMP_ARCH_X32"
          ]
        },
        {
          "architecture": "SCMP_ARCH_AARCH64",
          "subArchitectures": [
            "SCMP_ARCH_ARM"
          ]
        },
        {
          "architecture": "SCMP_ARCH_PPC64LE",
          "subArchitectures": [
            "SCMP_ARCH_PPC64",
            "SCMP_ARCH_PPC"
          ]
        },
        {
          "architecture": "SCMP_ARCH_S390X",
          "subArchitectures": [
            "SCMP_ARCH_S390"
          ]
        }
      ],
      "syscalls": [
        {
          "names": [
            "accept4",
            "arch_prctl",
            "bind",
            "bpf",
            "brk",
            "capget",
            "capset",
            "chdir",
            "clone3",
            "close",
            "connect",
            "dup3",
            "epoll_create1",
            "epoll_ctl",
            "epoll_pwait",
            "epoll_wait",
            "eventfd2",
            "execve",
            "faccessat2",
            "fchownat",
            "fcntl",
            "fstat",
            "fstatfs",
            "futex",
            "getcwd",
            "getdents64",
            "getgid",
            "getpeername",
            "getpid",
            "getppid",
            "getrandom",
            "getrlimit",
            "getsockname",
            "getsockopt",
            "gettid",
            "ioctl",
            "listen",
            "lseek",
            "madvise",
            "memfd_create",
            "mmap",
            "mprotect",
            "mremap",
            "munmap",
            "nanosleep",
            "newfstatat",
            "openat",
            "perf_event_open",
            "prctl",
            "pread64",
            "prlimit64",
            "read",
            "readlinkat",
            "rseq",
            "rt_sigaction",
            "rt_sigprocmask",
            "rt_sigreturn",
            "sched_getaffinity",
            "sched_yield",
            "seccomp",
            "set_robust_list",
            "set_tid_address",
            "setgid",
            "setgroups",
            "setrlimit",
            "setsockopt",
            "setuid",
            "sigaltstack",
            "socket",
            "stat",
            "statfs",
            "tgkill",
            "uname",
            "write"
          ],
          "action": "SCMP_ACT_ALLOW"
        }
      ]
    }
  bpfrecorder-apparmor.yaml: |
    apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
    kind: AppArmorProfile
    metadata:
      labels:
        spo.x-k8s.io/container-id: bpf-recorder
      name: bpfrecorder-apparmor
      namespace: security-profiles-operator
    spec:
      abstract:
        capability:
          allowedCapabilities:
          - bpf
          - chown
          - perfmon
          - sys_resource
        executable:
          allowedExecutables:
          - /security-profiles-operator
        filesystem:
          readOnlyPaths:
          - /proc/@{pid}/cgroup
          - /proc/@{pid}/maps
          - /proc/sys/net/core/somaxconn
          - /sys/devices/kprobe/type
          - /sys/devices/system/cpu/online
          - /sys/fs/bpf/
          - /sys/kernel/btf/vmlinux
          - /sys/kernel/debug/tracing/events/**/id
          - /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
          - /sys/kernel/security/lsm
          - /var/run/secrets/kubernetes.io/serviceaccount/**
          - /var/run/secrets/kubernetes.io/serviceaccount/**
          readWritePaths:
          - "ptrace (read),\n# ugly template injection hack"
          - /var/run/grpc/bpf-recorder.sock
        network:
          allowedProtocols:
            allowTcp: true
            allowUdp: true
      disabled: false
  json-enricher-log-volume-mount-path: /data/logs/jsonenricher
  json-enricher-log-volume-source.json: |-
    {
      "emptyDir": {
        "sizeLimit": "500Mi"
      }
    }
  security-profiles-operator.json: |
    {
      "defaultAction": "SCMP_ACT_ERRNO",
        "archMap": [
            {
                "architecture": "SCMP_ARCH_X86_64",
                "subArchitectures": [
                    "SCMP_ARCH_X86",
                    "SCMP_ARCH_X32"
                ]
            },
            {
                "architecture": "SCMP_ARCH_AARCH64",
                "subArchitectures": [
                    "SCMP_ARCH_ARM"
                ]
            },
            {
            "architecture": "SCMP_ARCH_PPC64LE",
                "subArchitectures": [
                    "SCMP_ARCH_PPC64",
                    "SCMP_ARCH_PPC"
                ]
            },
            {
                "architecture": "SCMP_ARCH_S390X",
                "subArchitectures": [
                    "SCMP_ARCH_S390"
                ]
            }
        ],
      "syscalls": [
        {
          "names": [
            "accept4",
            "arch_prctl",
            "bind",
            "brk",
            "capget",
            "capset",
            "chdir",
            "clone3",
            "close",
            "connect",
            "epoll_create1",
            "epoll_ctl",
            "epoll_pwait",
            "eventfd2",
            "execve",
            "exit_group",
            "faccessat2",
            "fcntl",
            "fstat",
            "fstatfs",
            "futex",
            "getcwd",
            "getdents64",
            "getpeername",
            "getpid",
            "getppid",
            "getrandom",
            "getrlimit",
            "getsockname",
            "getsockopt",
            "gettid",
            "inotify_add_watch",
            "inotify_init1",
            "listen",
            "madvise",
            "mkdirat",
            "mmap",
            "mprotect",
            "munmap",
            "nanosleep",
            "newfstatat",
            "openat",
            "prctl",
            "pread64",
            "prlimit64",
            "read",
            "readlinkat",
            "rseq",
            "rt_sigaction",
            "rt_sigprocmask",
            "rt_sigreturn",
            "sched_getaffinity",
            "sched_yield",
            "seccomp",
            "set_robust_list",
            "set_tid_address",
            "setgid",
            "setgroups",
            "setsockopt",
            "setuid",
            "sigaltstack",
            "socket",
            "stat",
            "statfs",
            "tgkill",
            "uname",
            "unshare",
            "unlinkat",
            "write"
          ],
          "action": "SCMP_ACT_ALLOW"
        }
      ]
    }
  selinuxd-image-mapping.json: |
    [
        {
            "regex":"(.*)(CoreOS).*([\\d+])\\.8[\\d+]\\.(.*)",
            "imageFromVar":"RELATED_IMAGE_SELINUXD_EL8"
        },
        {
            "regex":"(.*)(CoreOS).*([\\d+])\\.9[\\d+]\\.(.*)|(.*)(CoreOS)([\\s+])9\\.(.*)",
            "imageFromVar":"RELATED_IMAGE_SELINUXD_EL9"
        },
        {
            "regex":"Fedora \\d+",
            "imageFromVar":"RELATED_IMAGE_SELINUXD_FEDORA"
        }
    ]
  selinuxd.cil: |
    (block selinuxd
        (blockinherit container)
        (allow process process ( capability ( dac_override dac_read_search lease audit_write audit_control )))

        (allow process default_context_t ( dir ( add_name create getattr ioctl lock open read remove_name rmdir search setattr write )))
        (allow process default_context_t ( fifo_file ( getattr read write append ioctl lock open )))
        (allow process default_context_t ( file ( append create getattr ioctl lock map open read rename setattr unlink write )))
        (allow process default_context_t ( sock_file ( append getattr open read write )))
        (allow process etc_t ( dir ( add_name create getattr ioctl lock open read remove_name rmdir search setattr write watch )))
        (allow process etc_t ( fifo_file ( getattr read write append ioctl lock open )))
        (allow process etc_t ( file ( append create getattr ioctl lock map open read rename setattr unlink write )))
        (allow process etc_t ( sock_file ( append getattr open read write )))
        (allow process file_context_t ( dir ( add_name create getattr ioctl lock open read remove_name rmdir search setattr write )))
        (allow process file_context_t ( fifo_file ( getattr read write append ioctl lock open )))
        (allow process file_context_t ( file ( append create getattr ioctl lock map open read rename setattr unlink write )))
        (allow process file_context_t ( sock_file ( append getattr open read write )))
        (allow process security_t ( file ( append create getattr ioctl lock map open read rename setattr unlink write )))
        (allow process security_t ( security ( load_policy )))
        (allow process selinux_config_t ( dir ( add_name create getattr ioctl lock open read remove_name rename rmdir search setattr write )))
        (allow process selinux_config_t ( fifo_file ( getattr read write append ioctl lock open )))
        (allow process selinux_config_t ( file ( append create getattr ioctl lock map open read rename setattr unlink write )))
        (allow process selinux_config_t ( sock_file ( append getattr open read write )))
        (allow process selinux_login_config_t ( dir ( add_name create getattr ioctl lock open read remove_name rmdir search setattr write )))
        (allow process selinux_login_config_t ( fifo_file ( getattr read write append ioctl lock open )))
        (allow process selinux_login_config_t ( file ( append create getattr ioctl lock map open read rename setattr unlink write )))
        (allow process selinux_login_config_t ( sock_file ( append getattr open read write )))
        (allow process semanage_read_lock_t ( dir ( add_name create getattr ioctl lock open read remove_name rmdir search setattr write )))
        (allow process semanage_read_lock_t ( fifo_file ( getattr read write append ioctl lock open )))
        (allow process semanage_read_lock_t ( file ( append create getattr ioctl lock map open read rename setattr unlink write )))
        (allow process semanage_read_lock_t ( sock_file ( append getattr open read write )))
        (allow process semanage_store_t ( dir ( add_name create getattr ioctl lock open read rename remove_name rmdir search setattr write )))
        (allow process semanage_store_t ( fifo_file ( getattr read write append ioctl lock open )))
        (allow process semanage_store_t ( file ( append create getattr ioctl lock map open read rename setattr unlink write )))
        (allow process semanage_store_t ( sock_file ( append getattr open read write )))
        (allow process semanage_trans_lock_t ( dir ( add_name create getattr ioctl lock open read remove_name rmdir search setattr write )))
        (allow process semanage_trans_lock_t ( fifo_file ( getattr read write append ioctl lock open )))
        (allow process semanage_trans_lock_t ( file ( append create getattr ioctl lock map open read rename setattr unlink write )))
        (allow process semanage_trans_lock_t ( sock_file ( append getattr open read write )))
        (allow process sysfs_t ( dir ( add_name create getattr ioctl lock open read remove_name rmdir search setattr write )))
        (allow process sysfs_t ( fifo_file ( getattr read write append ioctl lock open )))
        (allow process sysfs_t ( file ( append create getattr ioctl lock map open read rename setattr unlink write )))
        (allow process sysfs_t ( sock_file ( append getattr open read write )))
    )
  selinuxrecording.cil: |
    (block selinuxrecording
      (blockinherit container)
      (typepermissive process)
    )
  spo-apparmor.yaml: |
    apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
    kind: AppArmorProfile
    metadata:
      labels:
        spo.x-k8s.io/container-id: security-profiles-operator
      name: spo-apparmor
      namespace: security-profiles-operator
    spec:
      abstract:
        capability:
          allowedCapabilities:
          - dac_override
          - dac_read_search
          - mac_admin
          - sys_admin
          - sys_chroot
        executable:
          allowedExecutables:
          - /security-profiles-operator
          - /usr/sbin/apparmor_parser
          - /sbin/apparmor_parser
        filesystem:
          readOnlyPaths:
          - /  # workaround for apparmor bug
          - /etc/apparmor/parser.conf
          - /proc/@{pid}/maps
          - /proc/@{pid}/mounts
          - /proc/sys/kernel/osrelease
          - /proc/sys/net/core/somaxconn
          - /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
          - /var/run/secrets/kubernetes.io/serviceaccount/**
          - /var/run/secrets/metrics/**
          - /sys/module/apparmor/parameters/enabled
          - /sys/devices/system/cpu/possible
          readWritePaths:
          - "ptrace (read),  # ugly template injection hack"
          - /var/run/grpc/metrics.sock
          - /tmp/aa_profile_bin_*
          - /etc/apparmor.d/**
          - /sys/kernel/security/apparmor/
          - /sys/kernel/security/apparmor/**
          - /var/lib/kubelet/seccomp/operator/**
        network:
          allowedProtocols:
            allowTcp: true
            allowUdp: true
      disabled: false
kind: ConfigMap
metadata:
  labels:
    app: security-profiles-operator
  name: security-profiles-operator-profile
