---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: security-profiles-operator
subjects:
- kind: ServiceAccount
  name: security-profiles-operator
  namespace: security-profiles-operator
roleRef:
  kind: ClusterRole
  name: security-profiles-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: security-profiles-operator
  name: security-profiles-operator
  namespace: security-profiles-operator
subjects:
- kind: ServiceAccount
  name: security-profiles-operator
roleRef:
  kind: Role
  name: security-profiles-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spod
subjects:
- kind: ServiceAccount
  name: spod
  namespace: security-profiles-operator
roleRef:
  kind: ClusterRole
  name: spod
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: security-profiles-operator
  name: spod
  namespace: security-profiles-operator
subjects:
- kind: ServiceAccount
  name: spod
  namespace: security-profiles-operator
roleRef:
  kind: Role
  name: spod
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spo-webhook
subjects:
- kind: ServiceAccount
  name: spo-webhook
  namespace: security-profiles-operator
roleRef:
  kind: ClusterRole
  name: spo-webhook
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: security-profiles-operator
  name: spo-webhook
  namespace: security-profiles-operator
subjects:
- kind: ServiceAccount
  name: spo-webhook
roleRef:
  kind: Role
  name: spo-webhook
  apiGroup: rbac.authorization.k8s.io
