apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.4
  creationTimestamp: null
  labels:
    app: security-profiles-operator
  name: seccompprofiles.security-profiles-operator.x-k8s.io
spec:
  group: security-profiles-operator.x-k8s.io
  names:
    kind: SeccompProfile
    listKind: SeccompProfileList
    plural: seccompprofiles
    shortNames:
    - sp
    singular: seccompprofile
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.status
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SeccompProfile is a cluster level specification for a seccomp profile. See https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#seccomp
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SeccompProfileSpec defines the desired state of SeccompProfile.
            properties:
              architectures:
                description: the architecture used for system calls
                items:
                  enum:
                  - SCMP_ARCH_X86
                  - SCMP_ARCH_X86_64
                  - SCMP_ARCH_X32
                  - SCMP_ARCH_ARM
                  - SCMP_ARCH_AARCH64
                  - SCMP_ARCH_MIPS
                  - SCMP_ARCH_MIPS64
                  - SCMP_ARCH_MIPS64N32
                  - SCMP_ARCH_MIPSEL
                  - SCMP_ARCH_MIPSEL64
                  - SCMP_ARCH_MIPSEL64N32
                  - SCMP_ARCH_PPC
                  - SCMP_ARCH_PPC64
                  - SCMP_ARCH_PPC64LE
                  - SCMP_ARCH_S390
                  - SCMP_ARCH_S390X
                  - SCMP_ARCH_PARISC
                  - SCMP_ARCH_PARISC64
                  - SCMP_ARCH_RISCV64
                  type: string
                type: array
              baseProfileName:
                description: name of base profile (in the same namespace) what will be unioned into this profile
                type: string
              defaultAction:
                description: the default action for seccomp
                enum:
                - SCMP_ACT_KILL
                - SCMP_ACT_KILL_PROCESS
                - SCMP_ACT_KILL_THREAD
                - SCMP_ACT_TRAP
                - SCMP_ACT_ERRNO
                - SCMP_ACT_TRACE
                - SCMP_ACT_ALLOW
                - SCMP_ACT_LOG
                type: string
              flags:
                description: list of flags to use with seccomp(2)
                items:
                  enum:
                  - SECCOMP_FILTER_FLAG_TSYNC
                  - SECCOMP_FILTER_FLAG_LOG
                  - SECCOMP_FILTER_FLAG_SPEC_ALLOW
                  type: string
                type: array
              syscalls:
                description: match a syscall in seccomp. While this property is OPTIONAL, some values of defaultAction are not useful without syscalls entries. For example, if defaultAction is SCMP_ACT_KILL and syscalls is empty or unset, the kernel will kill the container process on its first syscall
                items:
                  description: Syscall defines a syscall in seccomp.
                  properties:
                    action:
                      description: the action for seccomp rules
                      enum:
                      - SCMP_ACT_KILL
                      - SCMP_ACT_KILL_PROCESS
                      - SCMP_ACT_KILL_THREAD
                      - SCMP_ACT_TRAP
                      - SCMP_ACT_ERRNO
                      - SCMP_ACT_TRACE
                      - SCMP_ACT_ALLOW
                      - SCMP_ACT_LOG
                      type: string
                    args:
                      description: the specific syscall in seccomp
                      items:
                        description: Arg defines the specific syscall in seccomp.
                        properties:
                          index:
                            description: the index for syscall arguments in seccomp
                            minimum: 0
                            type: integer
                          op:
                            description: the operator for syscall arguments in seccomp
                            enum:
                            - SCMP_CMP_NE
                            - SCMP_CMP_LT
                            - SCMP_CMP_LE
                            - SCMP_CMP_EQ
                            - SCMP_CMP_GE
                            - SCMP_CMP_GT
                            - SCMP_CMP_MASKED_EQ
                            type: string
                          value:
                            description: the value for syscall arguments in seccomp
                            format: int64
                            minimum: 0
                            type: integer
                          valueTwo:
                            description: the value for syscall arguments in seccomp
                            format: int64
                            minimum: 0
                            type: integer
                        required:
                        - index
                        - op
                        type: object
                      maxItems: 6
                      type: array
                    errnoRet:
                      description: the errno return code to use. Some actions like SCMP_ACT_ERRNO and SCMP_ACT_TRACE allow to specify the errno code to return
                      type: string
                    names:
                      description: the names of the syscalls
                      items:
                        type: string
                      type: array
                  required:
                  - action
                  - names
                  type: object
                type: array
              targetWorkload:
                description: the type of application workload for which the profile is targeted. Will be a subdirectory in the profile path on disk.
                type: string
            required:
            - defaultAction
            - targetWorkload
            type: object
          status:
            description: SeccompProfileStatus contains status of the deployed SeccompProfile.
            properties:
              activeWorkloads:
                items:
                  type: string
                type: array
              path:
                type: string
              status:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.4
  creationTimestamp: null
  labels:
    app: security-profiles-operator
  name: selinuxpolicies.security-profiles-operator.x-k8s.io
spec:
  group: security-profiles-operator.x-k8s.io
  names:
    kind: SelinuxPolicy
    listKind: SelinuxPolicyList
    plural: selinuxpolicies
    singular: selinuxpolicy
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.usage
      name: Usage
      type: string
    - jsonPath: .spec.apply
      name: Apply
      type: boolean
    - jsonPath: .status.state
      name: State
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SelinuxPolicy is the Schema for the selinuxpolicies API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SelinuxPolicySpec defines the desired state of SelinuxPolicy.
            properties:
              apply:
                type: boolean
              policy:
                type: string
            type: object
          status:
            description: SelinuxPolicyStatus defines the observed state of SelinuxPolicy.
            properties:
              state:
                description: 'Represents the state that the policy is in. Can be: PENDING, IN-PROGRESS, INSTALLED or ERROR'
                type: string
              usage:
                description: Represents the string that the SelinuxPolicy object can be referenced as in a pod seLinuxOptions section.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: security-profiles-operator
  name: security-profiles-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: security-profiles-operator
  name: security-profiles-operator
  namespace: security-profiles-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: security-profiles-operator
  name: config-map-reader
  namespace: NS_REPLACE
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - nodes
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - security-profiles-operator.x-k8s.io
  resources:
  - seccompprofiles
  - selinuxpolicies
  verbs:
  - get
  - watch
  - list
  - update
  - patch
- apiGroups:
  - security-profiles-operator.x-k8s.io
  resources:
  - seccompprofiles/status
  - selinuxpolicies/status
  verbs:
  - get
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: security-profiles-operator
  name: config-map-reader-binding
  namespace: NS_REPLACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: config-map-reader
subjects:
- kind: ServiceAccount
  name: security-profiles-operator
  namespace: security-profiles-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: security-profiles-operator
  name: security-profiles-operator
  namespace: security-profiles-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - configmaps/finalizers
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resourceNames:
  - selinux-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: security-profiles-operator
  name: selinux-operator
  namespace: security-profiles-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: security-profiles-operator
subjects:
- kind: ServiceAccount
  name: security-profiles-operator
  namespace: security-profiles-operator
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: security-profiles-operator
  name: security-profiles-operator
  namespace: security-profiles-operator
spec:
  selector:
    matchLabels:
      app: security-profiles-operator
      name: security-profiles-operator
  template:
    metadata:
      annotations:
        container.seccomp.security.alpha.kubernetes.io/security-profiles-operator: localhost/security-profiles-operator.json
        openshift.io/scc: privileged
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      labels:
        app: security-profiles-operator
        name: security-profiles-operator
    spec:
      containers:
      - env:
        - name: RESTRICT_TO_NAMESPACE
          value: NS_REPLACE
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: gcr.io/k8s-staging-sp-operator/security-profiles-operator:latest
        imagePullPolicy: Always
        name: security-profiles-operator
        resources:
          limits:
            cpu: 300m
            ephemeral-storage: 200Mi
            memory: 128Mi
          requests:
            cpu: 100m
            ephemeral-storage: 50Mi
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 2000
          runAsUser: 2000
        volumeMounts:
        - mountPath: /var/lib/kubelet/seccomp/operator
          name: host-operator-volume
      initContainers:
      - args:
        - |
          set -euo pipefail

          if [ ! -d $KUBELET_SECCOMP_ROOT ]; then
            /bin/mkdir -m 0744 -p $KUBELET_SECCOMP_ROOT
          fi

          /bin/mkdir -p $OPERATOR_ROOT
          /bin/chmod 0744 $OPERATOR_ROOT

          if [ ! -L $OPERATOR_SYMLINK ]; then
            /bin/ln -s $OPERATOR_ROOT $OPERATOR_SYMLINK
          fi

          /bin/chown -R 2000:2000 $OPERATOR_ROOT
          cp -f -v /opt/seccomp-profiles/* $KUBELET_SECCOMP_ROOT
        command:
        - bash
        - -c
        env:
        - name: KUBELET_SECCOMP_ROOT
          value: /var/lib/kubelet/seccomp
        - name: OPERATOR_SYMLINK
          value: $(KUBELET_SECCOMP_ROOT)/operator
        - name: OPERATOR_ROOT
          value: /var/lib/security-profiles-operator
        image: bash:5.0
        name: non-root-enabler
        resources:
          limits:
            cpu: 250m
            ephemeral-storage: 50Mi
            memory: 64Mi
          requests:
            cpu: 100m
            ephemeral-storage: 10Mi
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            - FOWNER
            - FSETID
            - DAC_OVERRIDE
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsUser: 0
          seLinuxOptions:
            type: spc_t
        volumeMounts:
        - mountPath: /var/lib
          name: host-varlib-volume
        - mountPath: /opt/seccomp-profiles
          name: profile-configmap-volume
          readOnly: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: security-profiles-operator
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
      volumes:
      - hostPath:
          path: /var/lib
          type: Directory
        name: host-varlib-volume
      - hostPath:
          path: /var/lib/security-profiles-operator
          type: DirectoryOrCreate
        name: host-operator-volume
      - configMap:
          name: security-profiles-operator-profile
        name: profile-configmap-volume
---
apiVersion: v1
data:
  security-profiles-operator.json: |
    {
      "defaultAction": "SCMP_ACT_ERRNO",
      "architectures": ["SCMP_ARCH_X86_64", "SCMP_ARCH_X86", "SCMP_ARCH_X32"],
      "syscalls": [
        {
          "names": [
            "accept4",
            "arch_prctl",
            "bind",
            "brk",
            "clone",
            "close",
            "connect",
            "epoll_create1",
            "epoll_ctl",
            "epoll_pwait",
            "execve",
            "exit",
            "exit_group",
            "fcntl",
            "fstat",
            "futex",
            "getcwd",
            "getgid",
            "getpeername",
            "getpgrp",
            "getpid",
            "getppid",
            "getrandom",
            "getsockname",
            "getsockopt",
            "gettid",
            "getuid",
            "listen",
            "madvise",
            "membarrier",
            "mkdirat",
            "mlock",
            "mmap",
            "mprotect",
            "nanosleep",
            "newfstatat",
            "open",
            "openat",
            "pipe2",
            "pread64",
            "read",
            "readlinkat",
            "rt_sigaction",
            "rt_sigprocmask",
            "rt_sigreturn",
            "sched_getaffinity",
            "sched_yield",
            "setgid",
            "setsockopt",
            "set_tid_address",
            "setuid",
            "sigaltstack",
            "socket",
            "tgkill",
            "uname",
            "unlinkat",
            "write"
          ],
          "action": "SCMP_ACT_ALLOW"
        }
      ]
    }
kind: ConfigMap
metadata:
  labels:
    app: security-profiles-operator
  name: security-profiles-operator-profile
  namespace: security-profiles-operator
